name: translator_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  translator: ^1.0.0
  gap: ^3.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true


# assets:
#   - assets/
#   # - assets/a 1.png
# flutter:
  assets:
    - assets/
    - gif/

